### ISSUE TITLE
Use camera entity buttom to open camera will be unstoppable

### ISSUE THREAD

**Issue by ElvinChen12** [milaq/android_device_lge_p940#12]
If I use the camera button on the top of my LG P940  to open the camera function,  the camera will become non-stop and every key on the P940 will be shutter button (search, home, return, Power.....etc). i.e, I touch any key or button on my phone will pull the trigger.

But if I start the camera by the application icon in the system then Power button will transfer to shutter button, and the other key will remain regularly.

**Comment by milaq** [comment]
needs confirmation

**Comment by milaq** [comment]
closed until logs attached
