### ISSUE TITLE
Network Signal drops and never come back

### ISSUE THREAD

**Issue by saiz136** [milaq/android_device_lge_p940#14]
I have a low signal at home it even drops at times, however it doesn't return back the signal on the highest point of our house. Sometimes the signal comes back at full bar or switching Airplane mode on/off however it doesn't have a network (can't receive or make call/text message plus no 3G) A reboot is needed to return the signal rate.

**Comment by XperFD** [comment]
I'm facing the same issue.

**Comment by tom889** [comment]
No Signal, reboot still no signal.

**Comment by r4ngo** [comment]
Same here using Vodafone sim.
Even after powering off/on there is no signal, helps to activate airplane mode for a sec and after deactivating, signal is back. If this don´t work, then need to activate 2G only and after that it works, also back in HSPA mode.
With stock fw never had this problem and have a very good signal strengh.

**Comment by milaq** [comment]
should be fixed with
https://github.com/milaq/android_device_lge_p940/commit/78de70e9efb305ce91c54cb65b1058dfe7f52539
