### ISSUE TITLE
Call Volume Extremely High while using Wired Headset

### ISSUE THREAD

**Issue by XperFD** [milaq/android_device_lge_p940#15]
Call Volume Extremely High(full volume) while making or receiving GSM Phone Calls calls using Wired Headset. There is no control on volume if headset is used, the volume slider changes UP/DN as per key presses but it doesn't control volume. Sound level is so high that it can cause damage to ear. Strange thing is that this problem happens only during GSM calls. While using Music Player, Skype or other VOIP calls, this problem doesn't show up.

**Comment by milaq** [comment]
fixed by https://github.com/milaq/android_device_lge_p940/commit/6a34be1126554672b6b95d82acfc720f405dfc4a
