### ISSUE TITLE
aeroplane mode kills phone connectivity until reboot

### ISSUE THREAD

**Issue by milaq** [milaq/android_device_lge_p940#2]
after a manual rescan or device reboot it works again.

reason unknown atm

**Comment by frankfor85** [comment]
Is not necessary to reboot device: just after deactivate aeroplane mode, it's enough to activate mobile data (also with a widget) and all connectivity is restored in one second.

**Comment by milaq** [comment]
thanks for reporting.
toggling mobile data after leaving aeroplane mode does the trick.

maybe it has smth to do with the rmnet iface up/down routine. i'll investigate that further.

**Comment by YgrekIx** [comment]
In my case turning on and then off aeroplane mode or mobile data don't help. Only restart solve problem, of course temporary. It happen ever 1-3 days. So if You need any logs or something like debug informations just tell me so I can provide it. I don't use aeroplane mode at all, so in my case this is not initiator of problem I think.

**Comment by milaq** [comment]
hmmm, can you try another sim card/carrier?

**Comment by YgrekIx** [comment]
Unfortunately no, it start happening just after I install CM. Also I don't have/use any other provider sim. I think about going back to stock to confirm that it's only CM bug and not device.

**Comment by EleRam** [comment]
I have this problem too.

**Comment by milaq** [comment]
fixed by https://github.com/milaq/android_device_lge_p940/commit/b7f0273d4c265369d57bc7dac8bf2316de7a9772
